name       : python-idna
version    : 2.0
release    : 1
source     :
    - https://pypi.python.org/packages/source/i/idna/idna-2.0.tar.gz : 16199aad938b290f5be1057c0e1efc6546229391c23cea61ca940c115f7d3d3b
license    : BSD-3-Clause
summary    : A python library to support the Internationalised Domain Names in Applications.
description: |
    A python library to support the Internationalised Domain Names in Applications.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
    - python-setuptools
build      : |
    for py in "python" "python3" ; do
        ${py} setup.py build
    done
install    : |
    for py in "python" "python3" ; do
        ${py} setup.py install --root=%installroot% --no-compile -O0
    done
