name       : python-idna
version    : '3.3'
release    : 9
source     :
    - https://pypi.io/packages/source/i/idna/idna-3.3.tar.gz : 9d643ff0a55b762d5cdb124b8eaa99c66322e2157b69160bc32796e824360e6d
license    : BSD-3-Clause
component  : programming.python
summary    : A python library to support the Internationalised Domain Names in Applications
description: |
    A python library to support the Internationalised Domain Names in Applications.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
