name       : python-idna
version    : 2.8
release    : 4
source     :
    - https://pypi.io/packages/source/i/idna/idna-2.8.tar.gz : c357b3f628cf53ae2c4c05627ecc484553142ca23264e593d327bcde5e9c3407
license    : BSD-3-Clause
component  : programming.python
summary    : A python library to support the Internationalised Domain Names in Applications
description: |
    A python library to support the Internationalised Domain Names in Applications.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test
    %python3_test
