name       : python-idna
version    : '3.4'
release    : 11
source     :
    - https://pypi.io/packages/source/i/idna/idna-3.4.tar.gz : 814f528e8dead7d329833b91c5faa87d60bf71824cd12a7530b5526063d02cb4
homepage   : https://github.com/kjd/idna
license    : BSD-3-Clause
component  : programming.python
summary    : A python library to support the Internationalised Domain Names in Applications
description: |
    A python library to support the Internationalised Domain Names in Applications.
builddeps  :
    - python-build
    - python-flit-core
    - python-installer
    - python-packaging
    - python-pytest
setup      : |
    # Upstream issue https://github.com/kjd/idna/issues/129
    rm -rf setup.py
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
