name       : python-idna
version    : '3.2'
release    : 8
source     :
    - https://pypi.io/packages/source/i/idna/idna-3.2.tar.gz : 467fbad99067910785144ce333826c71fb0e63a425657295239737f7ecd125f3
license    : BSD-3-Clause
component  : programming.python
summary    : A python library to support the Internationalised Domain Names in Applications
description: |
    A python library to support the Internationalised Domain Names in Applications.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
