name       : python-idna
version    : 2.5
release    : 3
source     :
    - https://pypi.python.org/packages/d8/82/28a51052215014efc07feac7330ed758702fc0581347098a81699b5281cb/idna-2.5.tar.gz : 3cb5ce08046c4e3a560fc02f138d0ac63e00f8ce5901a56b32ec8b7994082aab
license    : BSD-3-Clause
component  : programming.python
summary    : A python library to support the Internationalised Domain Names in Applications.
description: |
    A python library to support the Internationalised Domain Names in Applications.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
