name       : python-idna
version    : '2.10'
release    : 6
source     :
    - https://pypi.io/packages/source/i/idna/idna-2.10.tar.gz : b307872f855b18632ce0c21c5e45be78c0ea7ae4c15c828c20788b26921eb3f6
license    : BSD-3-Clause
component  : programming.python
summary    : A python library to support the Internationalised Domain Names in Applications
description: |
    A python library to support the Internationalised Domain Names in Applications.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test
    %python3_test
